version: "3.7"

services:
  php:
    build:
      context: .
    image: bancos-brasil-value-object
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: php -S 0.0.0.0:8000 -t public/
    environment:
      APP_ENV: test
      XDEBUG_MODE: ${XDEBUG_MODE:-debug}
      XDEBUG_CONFIG: # ex: XDEBUG_CONFIG=client_host=host.docker.internal discover_client_host=false log_level=0
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=bancos.local}
